### ISSUE TITLE
API: Delete Function

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#10]
Does a delete function exist in the API, or copying a delete url? I'm using sharex with an adapted sr.ht script from [https://github.com/ShareX/CustomUploaders/blob/master/sr.ht.json ](https://github.com/ShareX/CustomUploaders/blob/master/sr.ht.json) and was hoping to add a copy Delete link function to this script.

**Comment by TheReverend403** [comment]
There's no function in the API, but you can just make a

**Comment by lwatsondev** [comment]
Added in 1.1.0. Deletion URL is sent in the JSON response for an upload as delete_url.
