### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#11]
It seems like I'm getting this error. I'm not really sure what triggered it but here's the log.
http://hastebin.com/iwifuranih.tex

**Comment by lwatsondev** [comment]
Open the `php artisan tinker` shell, type...

`\App\Models\UserPreferences::all();`

And post the output here, omitting any sensitive information.

Also what version of the software are you running? Please provide the
version number from `git describe --tags`.

**Comment by lwatsondev** [comment]
OK, I've reproduced the problem. Your user was created before I made preferences automatically create on registration.

Open `php artisan tinker` and type `foreach (\App\Models\User::all() as $user) { if (!$user->preferences) { \App\Models\UserPreferences::create(['user_id' => $user->id])->save(); } }`

This should create default prefs for any user missing them.

**Comment by camjac251** [comment]
Sorry for not replying. That seems to have fixed it.
