### ISSUE TITLE
Upload through subdomain

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#12]
Would it be possible to have all uploads go through a separate subdomain like with a.pste.pw being used for viewing the uploads? 

I'm using Cloudflare and their "Maximum Upload Size" is 100MB where I have a 5GB file limit on my nginx/php config. I was hoping to allow users to browse the main site and the a.\* subdomain on Cloudflare's network (CDN) and have all uploads go through the subdomain that's not connected to the cloudflare network. 

Or if it's possible, is there a way to split the upload into many requests? Cloudflare has a max of 100MB per request, so what if it uploaded it in "parts" and then pieced it together after it's all uploaded?

Also I added a reply to the "Url formatting" issue that I had opened, could you reopen it if possible?

**Comment by lwatsondev** [comment]
There doesn't need to be specific support for this, just open your routes file and create a [domain group](https://github.com/TheReverend403/uPste/blob/master/app/Http/routes.php#L139) containing the [API routes](https://github.com/TheReverend403/uPste/blob/master/app/Http/routes.php#L128)

**Comment by camjac251** [comment]
I attempted to implement this into my install and it works in the API info but the upload box on the site gives back an error `Server responded with 0 code.`

Could it be this [uPste/app/Http/Middleware/VerifyCsrfToken.php](https://github.com/TheReverend403/uPste/blob/master/app/Http/Middleware/VerifyCsrfToken.php) that's causing it?

**Comment by camjac251** [comment]
I've abandoned this idea in hopes to implement chunked uploads instead. I wanted to see if maybe pionl/laravel-chunk-upload would work but the rewrite would be better for this kind of thing
