### ISSUE TITLE
MIME type parsing

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#13]
I was thinking of this for some time now and wanted to ask you if you'd be possible.
I upload a lot of videos and audio files, some are able to play just fine in the browser but some (like wav files) aren't. I was thinking what if, nginx took any file under a.pste.pw that ended in certain extensions (mov, wav, flac, etc) and it would load up an html5 player that could play it. I'm not really sure how it'd all work, if it'd even be possible to replicate the same behavior that direct file playing would happen in the browser but it was something I thought of. It could parse the url into the player and load up the file in a compatible html5/flash player.

**Comment by lwatsondev** [comment]
This is additional complexity that I'm not really interested in. I don't intend for uPste to become a full file sharing suite like dropbox or the like with all the bells and whistles, I intend it to be simple to install, use and maintain. When a user clicks a link to a file, they should expect to get that exact file and nothing else. This allows files to be retreivable even with command line tools like `wget`.
