### ISSUE TITLE
thumbnails broken

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#14]
I think the last update with changing the file extensions to lowercase might've broken thumbnails.

**Comment by lwatsondev** [comment]
Did this breakage happen to coincide with a Firefox 46 upgrade?

**Comment by camjac251** [comment]
I don't think so. It seems to be the same on Chrome as well.

**Comment by lwatsondev** [comment]
Fixed in https://github.com/TheReverend403/uPste/commit/ef4a2dc3a5f22f323c82688faaade89cd6210caa
