### ISSUE TITLE
Merge domain and site_name variable into site_name

### ISSUE THREAD

**Issue by zhongfu** [TheReverend403/uPste#15]
In `.env`, there are two settings: `site_name` and `domain`. As far as I can see, `site_name` is only used in as the title for the index page (when not logged in), and as the sender name in emails sent from uPste. `domain`, on the other hand, is used to reference the site throughout the web interface and in emails to the user.

I have some minor gripes with this setup:
- Referring to the installation of uPste by its name (i.e. `site_name`) seems more appropriate than referring to by its domain throughout uPste
- The name of the `domain` variable is misleading -- although the attached comment in the config clears that up

Right now, users can simply set both variables to the same value. Regardless, having two different variables to refer to the site is mildly redundant; hence, I suggest that the two variables be merged into a single one, making references to the site more uniform.

Thanks for hearing me out!

(At the very least, using `site_name` for the navbar title to match the html title would make more sense than using `domain`.)

**Comment by lwatsondev** [comment]
Closed by a90d818e9941af83bbd936797175a5b17eaf81d4
