### ISSUE TITLE
Custom CSS changes

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#18]
I have some custom css changes in the /resources/views/layouts/master.blade.php as well as some changes in the /resources/views/account/resources.blade.php for adding a sharex script

Would there be any way to be able to add a child theme to this to override the default content and have it be as a seperate file so it doesnt conflict with git pulls?

**Comment by camjac251** [comment]
Alternatively, I could commit what I have to you and see if it gets merged, it's basically just adding a sharex script to the resources page and multiple sized favicons to the css header for mobile, tablet, computer, tv, etc.

**Comment by lwatsondev** [comment]
Just commit what you have. If anything needs changing, it can be fixed before merge.
