### ISSUE TITLE
Bug: Binary Files formatted as .bin

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#21]
I'm not sure if this is an intended feature change or not but if I say upload a file with the extension `.fbx` (3D stuff, like for maya), it'll format the url to .bin. It is a binary file but the original extension doesnt appear in the url which could cause confusion when linking items. `.exe` seems to format just fine (correctly to randomletters.exe even though its also a binary file.

**Comment by lwatsondev** [comment]
See if 4a09f95d72a2eda4eb5dd88769e22206e13d9677 helps.

**Comment by lwatsondev** [comment]
Closing due to no reply.

**Comment by camjac251** [comment]
Sorry about that, I just checked the older file and it still has the .bin extension

**Comment by lwatsondev** [comment]
This commit only affects new files.

**Comment by camjac251** [comment]
The commit did work, new files are showing as their original file extension rather than .bin
