### ISSUE TITLE
Resetting password link results in Page not found

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#25]
When you go to reset your password on the login screen, the email that is sent linking to `website.url/password/email/code` ends up showing "Page Not Found" in the same style as the down for maintenance when doing `composer update`. Does this happen for you too? I checked using the u.pste.pw site and it seems to result in the same error 40 - Page not found

**Comment by lwatsondev** [comment]
Try https://github.com/TheReverend403/uPste/commit/22e4f4fbb3f54e627eacacecaa21538f73000f56

**Comment by camjac251** [comment]
I don't think it worked, still getting the error.

**Comment by camjac251** [comment]
The same happens on the demo site as well still

**Comment by lwatsondev** [comment]
Fixed in https://github.com/TheReverend403/uPste/commit/180a6f67c93c688825f7d020e56b1b1330515791
