### ISSUE TITLE
Confirmation on API Delete Url

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#31]
Would it be possible to get a confirmation window for opening delete links from the API? For an extra addition to security?

**Comment by lwatsondev** [comment]
How exactly would this work? What if a client using the API doesn't even *have* a window?

The API has no business doing such things, this is entirely up to the API consumer.

**Comment by camjac251** [comment]
I should have said copying the deletion url instead. In ShareX, I have a deletion link field and when you go to it, it will delete the file without any confirmation.

The api field `$json:delete_url$`
