### ISSUE TITLE
Broken install after trying incompatible PHP version

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#36]
I might have broken my install of uPste but am unsure if it's requiring a reinstall or can be fixed manually. I've backed up the mysql DB (although didn't think to take one before php upgrade from 7.1 to 7.2). I ran composer update on php 7.2 and think possibly that is what broke packages possibly. Composer possibly getting packages newer than what is supported by 7.1?

```
 PHP Fatal error:  Uncaught ErrorException: file_put_contents(/path/upste/storage/framework/views/randomnumbersletters.php): failed to open stream: Permission denied in /path/upste/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:111
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/path...', 111, Array)
#1 /path/upste/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(111): file_put_contents('/path...', 'Client: <?php e...', 0)
#2 /path/upste/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(116): Illuminate\Filesystem\Filesystem->put('/path...', 'Client: <?php e...')
#3 /path/upste/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/path...')
#4 /path/upste/vendor/larav in /path/upste/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 111
```

This is what I see when I try loading the main frontend, although file links on the subdomain still work. I plan on doing a clean install to see if it fixes itself, do I just need to backup storage and the mysql DB for restoring? I've tried clearing the cache without any luck.

**Comment by lwatsondev** [comment]
> file_put_contents(/path/upste/storage/framework/views/randomnumbersletters.php): failed to open stream: Permission denied in /path/upste/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php

You need to give php write access to that folder.

I can't really help here though since you seem to be experiencing the issue in your own code.

**Comment by camjac251** [comment]
I can't believe I didn't see it at first. I was under the impression that php-fpm ran as the web server user by default 😕

I finally found the cause, which was simple. in my php-fpm `www.conf` file, I needed to change the default user:group from apache to my nginx user for it to work again.


Thank you
