### ISSUE TITLE
Open registration option

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#4]
Would it be possible to have as like a toggle option to have open registration? No admin approval required? Also thanks for adding user preferences, really nice thing there. I was thinking what if you did the same but for admin preferences, and you could change the same options if not more from the .env inside the panel. Lastly, with this new update, it seems to have fixed my php 503 error problem so thanks on that too.

**Comment by lwatsondev** [comment]
> Would it be possible to have as like a toggle option to have open registration? No admin approval required?

Added in https://github.com/TheReverend403/uPste/commit/69a163c1a542cf69e6bfc3c30fa774b3d95a9137

**Comment by camjac251** [comment]
That's just amazing! Thanks
