### ISSUE TITLE
Url formatting

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#5]
Would it be possible to change the way a url is formatted? I was thinking if the url structure would be something like `a.example.com/camjac251/originalfilename.extension` and if they are uploading the same filename then it'd format it like `a.example.com/camjac251/2/originalfilename.extension`
Or if that's not possible, would saving work as when you hit control s in the browser, it'll give you the original filename instead of the random characters like how puush does it or NotPomf (github).

**Comment by lwatsondev** [comment]
https://github.com/TheReverend403/uPste/commit/71a247f509d58feefe172f03ebea74c82bb3f608

**Comment by camjac251** [comment]
Would it not be possible to have the type of url structure above? I'd think it'd be more trusting to have an original filename in the URL than a randomly generated one because it would look less malicious. Like x5t2.png when it could be coolwebsite.png

**Comment by lwatsondev** [comment]
Again, totally defeats the intended use of uPste. The short URLs are for the convenience of people using terminal IRC clients like weechat for whom URLs might not even be clickable.
