### ISSUE TITLE
Memory (leak?) Issue in PHP

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#6]
My php.ini has its memory limit set to 128MB.

I tried uploading a 200MB file and it was uploading up until it "finished" giving out this code in red. [Image](http://a.upload.immo/6Wp.png)
[http://hastebin.com/etiwonovem.sm](http://hastebin.com/etiwonovem.sm)
Then I received an email from the system (upste/laravel) saying 

> Subject: [upload.immo] Application Exception
> 
> Client: My IP
> URL: http://upload.immo/api/upload
> 
> `Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 275642824 bytes) in /path/to/my/upste/realfolder/app/Http/Controllers/Api/UploadController.php:114
> Stack trace:
> # 0 {main}`

I was getting this even before the updates you pushed out today and yesterday.
I looked it up and people were saying that it was probably a memory leak caused by the php script.

_on a side note, I added you on steam and you accepted. Could we talk there, it'd be a lot easier with communication than GitHub issues._

**Comment by camjac251** [comment]
And here's what my nginx error log reads, couldn't find a php log (think it's embedded though in this one)
Sorry about the formatting :/ [http://hastebin.com/ehifevuxif.sm](http://hastebin.com/ehifevuxif.sm)

**Comment by lwatsondev** [comment]
Sounds a lot like you need to increase PHP's [memory limit](https://secure.php.net/manual/en/ini.core.php#ini.memory-limit) if you're uploading files of that size. There's no memory leak, it's just how PHP file uploads work. It has to store that 200MB somewhere in memory before it writes to disk.

**Comment by lwatsondev** [comment]
Actually, upon closer inspection, it's my fault for loading the whole file with file_get_contents(). Fix incoming,

**Comment by lwatsondev** [comment]
See if https://github.com/TheReverend403/uPste/commit/f3db1fa77e31c7424d57358c52811c5ef56f8f59 helps.

**Comment by camjac251** [comment]
That worked perfectly. Thanks
